---
apiVersion: loki.grafana.com/v1beta1
kind: AlertingRule
metadata:
  name: loki-operator-dev
  namespace: openshift-operators-redhat
  labels:
    openshift.io/cluster-monitoring: "true"
spec:
  tenantID: "infrastructure"
  groups:
    - name: Loki-Operator-Alerts
      interval: 10s
      rules:
        - alert: LokiOperatorHighReconciliationError
          expr: |
            1 > 0
          for: 0s
          labels:
            severity: info
            namespace: openshift-operators-redhat
            openshift_io_alert_source: platform
            prometheus: openshift-monitoring/k8s
          annotations:
            summary: High Loki Operator Reconciliation Errors
            description: A simple always firing alert to test Loki operator's ruler alertmanager configuration
---
apiVersion: loki.grafana.com/v1beta1
kind: RecordingRule
metadata:
  name: loki-operator-dev
  namespace: openshift-operators-redhat
  labels:
    openshift.io/cluster-monitoring: "true"
spec:
  tenantID: "infrastructure"
  groups:
    - name: LokiOperatorReconciliationErrors10m
      interval: 10m
      rules:
        - record: "loki:operator:errors:rate10m"
          expr: |
            sum(rate({kubernetes_namespace_name="openshift-operators-redhat", kubernetes_pod_name=~"loki-operator-controller-manager.*"} |= "error" [10m]))
