apiVersion: loki.grafana.com/v1beta1
kind: AlertingRule
metadata:
  name: lokistack-dev
  namespace: openshift-logging
  labels:
    loki.grafana.com/cluster-monitoring: "true"
spec:
  groups:
    - name: should_fire
      rules:
        - alert: HighPercentageError
          expr: |
            sum(rate({app="foo", env="production"} |= "error" [5m])) by (job)
              /
            sum(rate({app="foo", env="production"}[5m])) by (job)
              > 0.05
          for: 10m
          labels:
              severity: page
          annotations:
              summary: High request latency
    - name: credentials_leak
      rules:
        - alert: http-credentials-leaked
          annotations:
            message: "{{ $labels.job }} is leaking http basic auth credentials."
          expr: 'sum by (cluster, job, pod) (count_over_time({namespace="prod"} |~ "http(s?)://(\\w+):(\\w+)@" [5m]) > 0)'
          for: 10m
          labels:
            severity: critical
---
apiVersion: loki.grafana.com/v1beta1
kind: RecordingRule
metadata:
  name: lokistack-dev
  namespace: openshift-logging
  labels:
    loki.grafana.com/cluster-monitoring: "true"
spec:
  groups:
    - name: should_record
      interval: 10m
      rules:
        - record: "nginx:requests:rate10m"
          expr: |
            sum(rate({container="nginx"}[10m]))
---
apiVersion: loki.grafana.com/v1beta1
kind: AlertingRule
metadata:
  name: loki-operator-dev
  namespace: openshift-operators-redhat
  labels:
    loki.grafana.com/cluster-monitoring: "true"
spec:
  groups:
    - name: should_operator_fire_on_errors
      rules:
        - alert: HighPercentageError
          expr: |
            sum(rate({app="foo", env="production"} |= "error" [5m])) by (job)
              /
            sum(rate({app="foo", env="production"}[5m])) by (job)
              > 0.05
          for: 10m
          labels:
              severity: page
          annotations:
              summary: High request latency
    - name: credentials_operator_leak
      rules:
        - alert: http-credentials-leaked
          annotations:
            message: "{{ $labels.job }} is leaking http basic auth credentials."
          expr: 'sum by (cluster, job, pod) (count_over_time({namespace="prod"} |~ "http(s?)://(\\w+):(\\w+)@" [5m]) > 0)'
          for: 10m
          labels:
            severity: critical
---
apiVersion: loki.grafana.com/v1beta1
kind: RecordingRule
metadata:
  name: loki-operator-dev
  namespace: openshift-operators-redhat
  labels:
    loki.grafana.com/cluster-monitoring: "true"
spec:
  groups:
    - name: should_operator_record
      interval: 10m
      rules:
        - record: "nginx:requests:rate10m"
          expr: |
            sum(rate({container="nginx"}[10m]))
